.POSIX:
VERSION=1.2.3
BASEDIR=.
DESTDIR=
PREFIX=/usr/local
OUTDIR=$(BASEDIR)/dist
DOCDIR=$(OUTDIR)/doc
INTDIR=$(OUTDIR)/tmp
ARFLAGS=-cru
WARNFLAGS=-Wall -Wsign-conversion -pedantic
OPTFLAGS=-ffast-math -O3 -DNDEBUG
FPICFLAG=-fPIC
ALLFLAGS=$(WARNFLAGS) $(OPTFLAGS) $(FPICFLAG)
CFLAGS=$(ALLFLAGS) -std=c99
CXXFLAGS=$(ALLFLAGS) -std=c++03
REMOTE=git@github-xrf:xrf/coulomb_ho2d.git

# choice of implementation for alias
IMPL=am

.PHONY: alias all check check-compilers clean doc doc-upload install shared \
        shared-am static static-am uninstall

all: static shared alias

alias: $(OUTDIR)/libcoulombho2d.a $(OUTDIR)/libcoulombho2d.so

static: static-am

static-am: $(OUTDIR)/libcoulombho2d_am.a

shared: shared-am

shared-am: $(OUTDIR)/libcoulombho2d_am.so

install: all
	install -d $(DESTDIR)$(PREFIX)/include $(DESTDIR)$(PREFIX)/lib
	install -m644 -t $(DESTDIR)$(PREFIX)/include \
	    coulomb_ho2d.h
	install -m644 -t $(DESTDIR)$(PREFIX)/lib \
	    $(OUTDIR)/libcoulombho2d.a \
	    $(OUTDIR)/libcoulombho2d_am.a
	install -m755 -t $(DESTDIR)$(PREFIX)/lib \
	    $(OUTDIR)/libcoulombho2d.so \
	    $(OUTDIR)/libcoulombho2d_am.so \
	    $(OUTDIR)/libcoulombho2d_am.so.$(VERSION)

uninstall:
	rm -f \
	    $(DESTDIR)$(PREFIX)/include/coulomb_ho2d.h
	    $(DESTDIR)$(PREFIX)/lib/libcoulombho2d.a \
	    $(DESTDIR)$(PREFIX)/lib/libcoulombho2d_am.a
	    $(DESTDIR)$(PREFIX)/lib/libcoulombho2d.so \
	    $(DESTDIR)$(PREFIX)/lib/libcoulombho2d_am.so \
	    $(DESTDIR)$(PREFIX)/lib/libcoulombho2d_am.so.$(VERSION)

check:
	cd test && $(MAKE)

check-compilers:
	cppcheck coulomb_ho2d_am.c
	gcc $(WARNFLAGS) -x c -c coulomb_ho2d_am.c
	g++ $(WARNFLAGS) -x c -c coulomb_ho2d_am.c
	g++ $(WARNFLAGS) -std=c89 -x c -c coulomb_ho2d_am.c
	g++ $(WARNFLAGS) -std=c99 -x c -c coulomb_ho2d_am.c
	g++ $(WARNFLAGS) -x c++ -c coulomb_ho2d_am.c
	g++ $(WARNFLAGS) -std=c++03 -x c++ -c coulomb_ho2d_am.c
	g++ $(WARNFLAGS) -std=c++11 -x c++ -c coulomb_ho2d_am.c
	clang $(WARNFLAGS) -x c -c coulomb_ho2d_am.c
	clang++ $(WARNFLAGS) -x c -c coulomb_ho2d_am.c
	clang++ $(WARNFLAGS) -std=c89 -x c -c coulomb_ho2d_am.c
	clang++ $(WARNFLAGS) -std=c99 -x c -c coulomb_ho2d_am.c
	clang++ $(WARNFLAGS) -x c++ -c coulomb_ho2d_am.c
	clang++ $(WARNFLAGS) -std=c++03 -x c++ -c coulomb_ho2d_am.c
	clang++ $(WARNFLAGS) -std=c++11 -x c++ -c coulomb_ho2d_am.c
	rm coulomb_ho2d_am.o

clean:
	rm -fr $(DOCDIR) $(OUTDIR) $(INTDIR)

doc:
	mkdir -p $(DOCDIR)
	doxygen

doc-upload: doc $(DOCDIR)/.git/config
	cd $(DOCDIR) \
	  && git add -A \
	  && git commit --amend -q -m Autogenerated \
	  && git push -f origin master:gh-pages

$(DOCDIR)/.git/config:
	mkdir -p $(DOCDIR)
	cd $(DOCDIR) \
	  && git init \
	  && git config user.name Bot \
	  && git config user.email "<>" \
	  && git commit -m _ --allow-empty \
	  && git remote add origin $(REMOTE)

$(OUTDIR)/libcoulombho2d.a: $(OUTDIR)/libcoulombho2d_$(IMPL).a
	cp -f $(OUTDIR)/libcoulombho2d_$(IMPL).a $@

$(OUTDIR)/libcoulombho2d.so: $(OUTDIR)/libcoulombho2d_$(IMPL).so
	ln -fs libcoulombho2d_$(IMPL).so $@

$(OUTDIR)/libcoulombho2d_am.a: \
    $(INTDIR)/coulomb_ho2d_am.o
	mkdir -p $(OUTDIR)
	$(AR) $(ARFLAGS) $@ \
	      $(INTDIR)/coulomb_ho2d_am.o

$(OUTDIR)/libcoulombho2d_am.so: \
    $(OUTDIR)/libcoulombho2d_am.so.$(VERSION)
	ln -fs libcoulombho2d_am.so.$(VERSION) $@

$(OUTDIR)/libcoulombho2d_am.so.$(VERSION): \
    $(INTDIR)/coulomb_ho2d_am.o
	mkdir -p $(OUTDIR)
	$(CC) -shared -Wl,-soname,libcoulombho2d_am.so.$(VERSION) -o $@ \
	      $(INTDIR)/coulomb_ho2d_am.o

$(INTDIR)/coulomb_ho2d_am.o: coulomb_ho2d_am.c
	mkdir -p $(INTDIR)
	$(CC) $(CFLAGS) -o $@ -c coulomb_ho2d_am.c
