BASEDIR=.
OUTDIR=$(BASEDIR)/dist/
DOCDIR=$(OUTDIR)/doc/
INTDIR=$(OUTDIR)/tmp
ARFLAGS=-cru
WARNFLAGS=-Wall -Wsign-conversion -pedantic
CFLAGS=$(WARNFLAGS) -std=c99 -O3 -ffast-math -DNDEBUG
REMOTE=git@github-xrf:xrf/coulomb_ho2d.git

lib: $(OUTDIR)/libcoulombho2d.a

all: lib test

$(OUTDIR)/libcoulombho2d.a: \
    $(INTDIR)/coulomb_ho2d_am.o \
    $(INTDIR)/coulomb_ho2d_compat.o
	mkdir -p $(OUTDIR)
	$(AR) $(ARFLAGS) $(OUTDIR)/libcoulombho2d.a \
	      $(INTDIR)/coulomb_ho2d_am.o \
	      $(INTDIR)/coulomb_ho2d_compat.o

$(INTDIR)/coulomb_ho2d_am.o: coulomb_ho2d_am.c
	mkdir -p $(INTDIR)
	$(CC) $(CFLAGS) -o $@ -c coulomb_ho2d_am.c

$(INTDIR)/coulomb_ho2d_compat.o: coulomb_ho2d_compat.c
	mkdir -p $(INTDIR)
	$(CC) $(CFLAGS) -o $@ -c coulomb_ho2d_compat.c

test:
	cd test && make

test-compilers:
	gcc $(WARNFLAGS) -x c -c coulomb_ho2d_am.c
	g++ $(WARNFLAGS) -x c -c coulomb_ho2d_am.c
	g++ $(WARNFLAGS) -std=c89 -x c -c coulomb_ho2d_am.c
	g++ $(WARNFLAGS) -std=c99 -x c -c coulomb_ho2d_am.c
	g++ $(WARNFLAGS) -x c++ -c coulomb_ho2d_am.c
	g++ $(WARNFLAGS) -std=c++03 -x c++ -c coulomb_ho2d_am.c
	g++ $(WARNFLAGS) -std=c++11 -x c++ -c coulomb_ho2d_am.c
	clang $(WARNFLAGS) -x c -c coulomb_ho2d_am.c
	clang++ $(WARNFLAGS) -x c -c coulomb_ho2d_am.c
	clang++ $(WARNFLAGS) -std=c89 -x c -c coulomb_ho2d_am.c
	clang++ $(WARNFLAGS) -std=c99 -x c -c coulomb_ho2d_am.c
	clang++ $(WARNFLAGS) -x c++ -c coulomb_ho2d_am.c
	clang++ $(WARNFLAGS) -std=c++03 -x c++ -c coulomb_ho2d_am.c
	clang++ $(WARNFLAGS) -std=c++11 -x c++ -c coulomb_ho2d_am.c
	gcc $(WARNFLAGS) -x c -c coulomb_ho2d_compat.c
	g++ $(WARNFLAGS) -x c -c coulomb_ho2d_compat.c
	g++ $(WARNFLAGS) -std=c89 -x c -c coulomb_ho2d_compat.c
	g++ $(WARNFLAGS) -std=c99 -x c -c coulomb_ho2d_compat.c
	g++ $(WARNFLAGS) -x c++ -c coulomb_ho2d_compat.c
	g++ $(WARNFLAGS) -std=c++03 -x c++ -c coulomb_ho2d_compat.c
	g++ $(WARNFLAGS) -std=c++11 -x c++ -c coulomb_ho2d_compat.c
	clang $(WARNFLAGS) -x c -c coulomb_ho2d_compat.c
	clang++ $(WARNFLAGS) -x c -c coulomb_ho2d_compat.c
	clang++ $(WARNFLAGS) -std=c89 -x c -c coulomb_ho2d_compat.c
	clang++ $(WARNFLAGS) -std=c99 -x c -c coulomb_ho2d_compat.c
	clang++ $(WARNFLAGS) -x c++ -c coulomb_ho2d_compat.c
	clang++ $(WARNFLAGS) -std=c++03 -x c++ -c coulomb_ho2d_compat.c
	clang++ $(WARNFLAGS) -std=c++11 -x c++ -c coulomb_ho2d_compat.c

doc: $(DOCDIR)/.git/config
	doxygen
	cd $(DOCDIR) \
	  && git add -A \
	  && git commit --amend -q -m Autogenerated --author="Bot <>" \
	  && git push -f origin master:gh-pages

$(DOCDIR)/.git/config:
	mkdir -p $(DOCDIR)
	cd $(DOCDIR) \
	  && git init \
	  && git commit -m Initial --allow-empty \
	  && git remote add origin $(REMOTE)

clean:
	rm -fr $(OUTDIR) $(INTDIR) $(DOCDIR)

.PHONY: clean test test-compilers
